workflow:
  build:
    strategy:
      # parallel: 5
      
      # fail-fast: false
      matrix:
        command: [ 'ping 127.0.0.1 -n 10', 'dir', 'not_a_command']

    runs-on:
      pool: default

    actions:  
    - run: ${{ matrix.command }}

    # - run: set Job_Position
    #   env:
    #    Job_Position: ${{ strategy['job-index'] }}

    # - run: set Job_Position
    #   name: printenv_name
    #   id: printenv_id
    #   if: succeeded()
    #   env:
    #    Job_Position: ${{ strategy['job-index'] }}
    #   working-directory: c:\
    
    # - uses: bryanmacfarlane/node-config@master
    #   with:
    #     version: ${{ strategy.matrix.nodeVersion }}

    # - uses: 'docker://ubuntu:16.04'
    #   if: succeeded()
    #   with:
    #     entryPoint: /bin/bash
    #     args: -c printenv
    #   env:
    #     foo: bar
    # - uses: TingluoHuang/npm@master
    #   name: npm_version
    #   with:
    #     args: version
    # - uses: ./npm
    #   name: npm_version_local
    #   with:
    #     args: version
    # - uses: actions/aws/cli@master
    #   id: cli_id
    #   with:
    #     args: --output text --color off help
    
    
