workflow:
  build:
    # strategy:
      # parallel: 3
      
      # fail-fast: false
      # matrix:
      #   command: [ 'ping 127.0.0.1 -n 60', 'not_a_command']

    runs-on:
      pool: default

    actions:
    - checkout: true
      fetch-depth: 5
      lfs: true

    - checkout: actions/npm@master

    - checkout: TingluoHuang/main@v3

    - run: set
    # - run: ${{ matrix.command }}
    
    # - run: set
    #   env:
    #    Job_Position: ${{ strategy['job-index'] }}
    #    Job_Parallelism: ${{ parallel }}

    # - run: set Job_Position
    #   name: printenv_name
    #   id: printenv_id
    #   if: succeeded()
    #   env:
    #    Job_Position: ${{ strategy['job-index'] }}
    #   working-directory: c:\
    
    # - uses: bryanmacfarlane/node-config@master
    #   with:
    #     version: ${{ strategy.matrix.nodeVersion }}

    # - uses: 'docker://ubuntu:16.04'
    #   if: succeeded()
    #   with:
    #     entryPoint: /bin/bash
    #     args: -c printenv
    #   env:
    #     foo: bar
    # - uses: TingluoHuang/npm@master
    #   name: npm_version
    #   with:
    #     args: version
    # - uses: ./npm
    #   name: npm_version_local
    #   with:
    #     args: version
    # - uses: actions/aws/cli@master
    #   id: cli_id
    #   with:
    #     args: --output text --color off help
    
    
