workflow:
  build:
    actions:
    - run: printenv
      name: printenv_name
      id: printenv_id
      if: succeeded()
      env:
        foo: bar
    - uses: 'docker://ubuntu:16.04'
      if: succeeded()
      with:
        entryPoint: /bin/bash
        args: -c printenv
      env:
        foo: bar
    - uses: actions/npm@master
      name: npm_version
      with:
        args: version
    - uses: actions/aws/cli@master
      id: cli_id
      with:
        args: --version
    
