jobs:
  build:
    runs-on: ubuntu-16.04

    actions:
    - checkout: true
      fetch-depth: 5
      submodules: true
      path: myrepo

    - checkout: actions/npm@master

    - checkout: TingluoHuang/lfstest-manyfiles@master
      lfs: true

    - run: ls -l "$GITHUB_WORKSPACE/../"

    - uses: 'docker://ubuntu:16.04'
      with:
        entryPoint: /bin/bash
        args: -c printenv
      env:
        foo: bar
        




















# jobs:
#   build:
#     strategy:
#       # parallel: 3
      
#       # fail-fast: false
#       matrix:
#         nodeVersion: [ '10' ]
#         # command: [ 'ping 127.0.0.1 -n 60', 'not_a_command']

#     runs-on: ubuntu-16.04

#     actions:
#     # - checkout: false

#     - checkout: true
#       fetch-depth: 5
#       submodules: true
#       path: foo

#     - checkout: actions/npm@master

#     - checkout: TingluoHuang/main@v3

#     - run: set

#     - run: ls "$GITHUB_WORKSPACE/../"
#     # - run: ${{ matrix.command }}
    
#     # - run: set
#     #   env:
#     #    Job_Position: ${{ strategy['job-index'] }}
#     #    Job_Parallelism: ${{ parallel }}

#     # - run: set Job_Position
#     #   name: printenv_name
#     #   id: printenv_id
#     #   if: succeeded()
#     #   env:
#     #    Job_Position: ${{ strategy['job-index'] }}
#     #   working-directory: c:\
    
#     - uses: bryanmacfarlane/node-config@master
#       with:
#         version: ${{ matrix.nodeVersion }}

#     - uses: 'docker://ubuntu:16.04'
#       if: succeeded()
#       with:
#         entryPoint: /bin/bash
#         args: -c printenv
#       env:
#         foo: bar
#     - uses: TingluoHuang/npm@master
#       name: npm_version
#       with:
#         args: version
#     # - uses: ./npm
#     #   name: npm_version_local
#     #   with:
#     #     args: version
#     - uses: actions/aws/cli@master
#       id: cli_id
#       with:
#         args: --output text --color off help
    
    
