name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - uses: actions/github-script@0.3.0
      with:
        debug: true
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          console.log("hello")
          const content = await github.repos.getContents({
            owner: 'TingluoHuang',
            repo: 'main',
            path: './.vsts/microsoft.yml'
          })
