name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
    - uses: actions/github-script@0.3.0
      with:
        script: |
          const content = github.repos.getContents({"${{github.repository}}", "", ".vsts/microsoft.yml", "f3ac01604f8f20839e074402cece62300c4f6c06"})
          console.log(content)
